"""The exported design tokens stay in step with the stylesheet they describe.

`docs/design/tokens/*.json` is the W3C Design Tokens (DTCG) export that Penpot
imports natively and that Storybook's "Design Tokens/Colours" story renders
from. It is generated by `npm run audit:tokens` out of
`static/visual-system.css`, and nothing makes anyone re-run it.

That is a quiet failure. Adding the semantic status ramp to visual-system.css
left the export with no `warning` token at all and only the gradients for
`success` and `info` -- so a Penpot import would have handed a designer a
palette missing the very thing the palette decision had just settled, and the
Colours story would have agreed with it. Nothing was broken; the handoff was
just describing a stylesheet that no longer existed.

So: every colour token the canonical layer declares must be in the export,
with the same value. The direction matters -- the export may hold *more* than
the light theme declares, because it also carries the dark set and a few
composed tokens -- so this checks coverage and agreement, not equality.

    uv run pytest tests/test_design_token_export.py -q

If it fails, run `npm run audit:tokens` and commit the result.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "packages/noodle-web/src/noodle_web/static/visual-system.css"
TOKENS_DIR = ROOT / "docs/design/tokens"

# A token whose value is a gradient, a shadow or a var() chain is composed
# rather than a colour, and the exporter treats those separately.
_HEX = re.compile(r"^#[0-9a-fA-F]{3,8}$")


def _declared(block: str) -> dict[str, str]:
    """`--np-*: <value>` pairs in one CSS block."""
    out = {}
    for name, value in re.findall(r"(--np-[a-z0-9-]+)\s*:\s*([^;]+);", block):
        out[name] = value.strip()
    return out


def _canonical_light() -> dict[str, str]:
    css = CANONICAL.read_text()
    # Everything before the dark block is the light theme.
    head = css[: css.index('[data-theme="dark"]')]
    return _declared(head)


def _exported() -> dict[str, str]:
    path = TOKENS_DIR / "color-light.json"
    if not path.exists():
        pytest.skip("token export not generated")

    flat: dict[str, str] = {}

    def walk(node, prefix=""):
        for key, value in node.items():
            if not isinstance(value, dict):
                continue
            if "$value" in value:
                flat[f"{prefix}{key}"] = str(value["$value"])
            else:
                walk(value, f"{prefix}{key}.")

    walk(json.loads(path.read_text()))
    return flat


def test_every_plain_colour_token_is_exported():
    declared = _canonical_light()
    exported = _exported()
    # Match on the trailing segment: the export namespaces tokens into sets,
    # the stylesheet does not.
    by_leaf = {name.rsplit(".", 1)[-1]: value for name, value in exported.items()}

    missing = []
    for name, value in sorted(declared.items()):
        if not _HEX.match(value):
            continue  # composed, aliased or non-colour
        leaf = name.removeprefix("--np-")
        if leaf not in by_leaf:
            missing.append(f"{name}: {value}")

    assert not missing, (
        "these colour tokens are declared in visual-system.css but absent from "
        "docs/design/tokens/color-light.json, so Penpot and Storybook would "
        "show a palette the app does not use:\n  "
        + "\n  ".join(missing)
        + "\n\nRun `npm run audit:tokens` and commit the result."
    )


def test_exported_values_match_the_stylesheet():
    declared = _canonical_light()
    by_leaf = {name.rsplit(".", 1)[-1]: value for name, value in _exported().items()}

    wrong = []
    for name, value in sorted(declared.items()):
        if not _HEX.match(value):
            continue
        leaf = name.removeprefix("--np-")
        got = by_leaf.get(leaf)
        if got is not None and got.strip().lower() != value.strip().lower():
            wrong.append(f"{name}: stylesheet {value}, export {got}")

    assert not wrong, (
        "the token export disagrees with visual-system.css:\n  "
        + "\n  ".join(wrong)
        + "\n\nRun `npm run audit:tokens` and commit the result."
    )


# What a DTCG `color` token may hold: a hex, a CSS colour function, or a
# keyword. Anything else typed `color` -- a duration, a gradient, a length --
# is what made Penpot's import fail and had to be dropped by hand.
_COLOUR_VALUE = re.compile(
    r"^(#[0-9a-fA-F]{3,8}"
    r"|(rgba?|hsla?|hwb|lab|lch|oklab|oklch|color)\(.*\)"
    r"|transparent|currentcolor)$",
    re.IGNORECASE,
)

_VALUE_SHAPE = {
    "duration": re.compile(r"^(\d*\.)?\d+m?s$"),
    "cubicBezier": re.compile(r"^cubic-bezier\(.*\)$"),
    "dimension": re.compile(r"^-?(\d*\.)?\d+(px|rem|em|%|vh|vw|ch|ex)?$"),
}


def _token_files() -> dict[str, dict]:
    files = {}
    for name in ("core", "color-light", "color-dark"):
        path = TOKENS_DIR / f"{name}.json"
        if not path.exists():
            pytest.skip("token export not generated")
        files[name] = json.loads(path.read_text())
    return files


def _leaves(node, prefix=""):
    for key, value in node.items():
        if not isinstance(value, dict):
            continue
        if "$value" in value:
            yield f"{prefix}{key}", value
        else:
            yield from _leaves(value, f"{prefix}{key}.")


def test_every_colour_typed_token_has_a_colour_value():
    wrong = [
        f"{set_name}/{name}: {token['$value']}"
        for set_name, tokens in _token_files().items()
        for name, token in _leaves(tokens)
        if token.get("$type") == "color"
        and not _COLOUR_VALUE.match(str(token["$value"]).strip())
    ]
    assert not wrong, (
        "these tokens are typed `color` but their value is not a colour, so "
        "Penpot's import rejects them:\n  "
        + "\n  ".join(wrong)
        + "\n\nFix categorize() in scripts/token-audit.mjs and re-run "
        "`npm run audit:tokens`."
    )


def test_typed_values_have_the_shape_their_type_claims():
    wrong = []
    for set_name, tokens in _token_files().items():
        for name, token in _leaves(tokens):
            shape = _VALUE_SHAPE.get(token.get("$type"))
            if shape and not shape.match(str(token["$value"]).strip()):
                wrong.append(f"{set_name}/{name} ({token['$type']}): {token['$value']}")
    assert not wrong, "tokens whose value does not match their $type:\n  " + "\n  ".join(wrong)


def test_no_gradient_reaches_the_export():
    # Penpot colour tokens cannot hold a gradient, and a CSS gradient is not a
    # DTCG `gradient` (a list of stops), so the exporter leaves them out.
    leaked = [
        f"{set_name}/{name}"
        for set_name, tokens in _token_files().items()
        for name, token in _leaves(tokens)
        if "gradient(" in str(token["$value"])
    ]
    assert not leaked, "gradients in the token export:\n  " + "\n  ".join(leaked)
