"""The exported design tokens stay in step with the stylesheet they describe.

`docs/design/tokens/*.json` is the W3C Design Tokens (DTCG) export that Penpot
imports natively and that Storybook's "Design Tokens/Colours" story renders
from. It is generated by `npm run audit:tokens` out of
`static/visual-system.css`, and nothing makes anyone re-run it.

That is a quiet failure. Adding the semantic status ramp to visual-system.css
left the export with no `warning` token at all and only the gradients for
`success` and `info` -- so a Penpot import would have handed a designer a
palette missing the very thing the palette decision had just settled, and the
Colours story would have agreed with it. Nothing was broken; the handoff was
just describing a stylesheet that no longer existed.

So: every colour token the canonical layer declares must be in the export,
with the same value. The direction matters -- the export may hold *more* than
the light theme declares, because it also carries the dark set and a few
composed tokens -- so this checks coverage and agreement, not equality.

    uv run pytest tests/test_design_token_export.py -q

If it fails, run `npm run audit:tokens` and commit the result.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "packages/noodle-web/src/noodle_web/static/visual-system.css"
TOKENS_DIR = ROOT / "docs/design/tokens"

# A token whose value is a gradient, a shadow or a var() chain is composed
# rather than a colour, and the exporter treats those separately.
_HEX = re.compile(r"^#[0-9a-fA-F]{3,8}$")


def _declared(block: str) -> dict[str, str]:
    """`--np-*: <value>` pairs in one CSS block."""
    out = {}
    for name, value in re.findall(r"(--np-[a-z0-9-]+)\s*:\s*([^;]+);", block):
        out[name] = value.strip()
    return out


def _canonical_light() -> dict[str, str]:
    css = CANONICAL.read_text()
    # Everything before the dark block is the light theme.
    head = css[: css.index('[data-theme="dark"]')]
    return _declared(head)


def _exported() -> dict[str, str]:
    path = TOKENS_DIR / "color-light.json"
    if not path.exists():
        pytest.skip("token export not generated")

    flat: dict[str, str] = {}

    def walk(node, prefix=""):
        for key, value in node.items():
            if not isinstance(value, dict):
                continue
            if "$value" in value:
                flat[f"{prefix}{key}"] = str(value["$value"])
            else:
                walk(value, f"{prefix}{key}.")

    walk(json.loads(path.read_text()))
    return flat


def test_every_plain_colour_token_is_exported():
    declared = _canonical_light()
    exported = _exported()
    # Match on the trailing segment: the export namespaces tokens into sets,
    # the stylesheet does not.
    by_leaf = {name.rsplit(".", 1)[-1]: value for name, value in exported.items()}

    missing = []
    for name, value in sorted(declared.items()):
        if not _HEX.match(value):
            continue  # composed, aliased or non-colour
        leaf = name.removeprefix("--np-")
        if leaf not in by_leaf:
            missing.append(f"{name}: {value}")

    assert not missing, (
        "these colour tokens are declared in visual-system.css but absent from "
        "docs/design/tokens/color-light.json, so Penpot and Storybook would "
        "show a palette the app does not use:\n  "
        + "\n  ".join(missing)
        + "\n\nRun `npm run audit:tokens` and commit the result."
    )


def test_exported_values_match_the_stylesheet():
    declared = _canonical_light()
    by_leaf = {name.rsplit(".", 1)[-1]: value for name, value in _exported().items()}

    wrong = []
    for name, value in sorted(declared.items()):
        if not _HEX.match(value):
            continue
        leaf = name.removeprefix("--np-")
        got = by_leaf.get(leaf)
        if got is not None and got.strip().lower() != value.strip().lower():
            wrong.append(f"{name}: stylesheet {value}, export {got}")

    assert not wrong, (
        "the token export disagrees with visual-system.css:\n  "
        + "\n  ".join(wrong)
        + "\n\nRun `npm run audit:tokens` and commit the result."
    )
