// Noodle Planner Database Schema
// DBML Documentation: https://dbml.dbdiagram.io/docs

Project NoodlePlanner {
  database_type: 'N/A'
  Note: 'NoodlePlanner is a stateless application. All data lives in the browser as markdown. No database is used.'
}
