"""Noodle Core - Scheduling engine and format conversion utilities."""

from .scheduling_engine import (
    text_to_markdown_table,
    yaml_to_markdown_table,
    export_to_excel,
    export_to_csv,
    export_timeline_to_powerpoint,
    export_report_to_powerpoint,
    export_portfolio_to_powerpoint,
    export_to_pdf,
    analyze_plan,
    get_next_working_day,
    add_working_days,
    parse_duration,
    extract_metadata,
    detect_dependency_loops,
    schedule_tasks,
    render_custom_timeline,
    calculate_rag_status,
    rag_status_to_colour,
    parse_resource_mappings,
    parse_resource_roles,
    parse_stakeholders_from_frontmatter,
    calculate_evm,
    natural_language_to_yaml,
    inherit_summary_resources,
    parse_recurrence,
    generate_recurrence_occurrences,
    MAX_TASK_COUNT,
    MAX_NESTING_DEPTH,
    MAX_TASK_NAME_LENGTH,
)

from .format_converter import (
    convert_plan_format_to_standard,
    extract_title_from_frontmatter,
    extract_highlights,
    strip_highlights,
    generate_highlights_text,
    update_plan_highlights,
    extract_raid_log,
    strip_raid_log,
    parse_raid_markdown,
    generate_raid_log_text,
    update_plan_raid_log,
    extract_budget,
    strip_budget,
    parse_budget_markdown,
    extract_comms_plan,
    strip_comms,
    parse_comms_markdown,
    generate_comms_plan_text,
    update_plan_comms,
    export_comms_to_docx,
    extract_benefits,
    strip_benefits,
    extract_baseline,
    strip_baseline,
    parse_baseline_markdown,
    generate_baseline_text,
    update_plan_baseline,
    extract_benefits,
    strip_benefits,
    parse_benefits_markdown,
    extract_lessons,
    strip_lessons,
    parse_lessons_markdown,
    generate_lessons_text,
    update_plan_lessons,
    extract_whiteboard,
    strip_whiteboard,
    parse_whiteboard_markdown,
    validate_whiteboard_rows,
    generate_whiteboard_text,
    update_plan_whiteboard,
    extract_parking_lot,
    strip_parking_lot,
    parse_parking_lot_markdown,
    generate_parking_lot_text,
    update_plan_parking_lot,
)

from .excel_importer import (
    analyze_workbook,
    convert_excel_to_markdown,
    convert_planner_to_markdown,
    detect_planner_worksheet,
    parse_planner_duration,
    parse_planner_dependency,
)

from .mpp_writer import export_to_mpp, MppTemplateError
from .msproject import (
    export_to_msproject_xml,
    import_from_msproject_xml,
    import_from_mpp,
    _check_mpp_available,
    _check_mpxj_available,  # backwards-compatible alias
)

from .front_matter_parser import FrontMatterParser

__version__ = "1.0.0"

__all__ = [
    # Scheduling engine
    "text_to_markdown_table",
    "yaml_to_markdown_table",
    "export_to_excel",
    "export_to_csv",
    "export_timeline_to_powerpoint",
    "export_portfolio_to_powerpoint",
    "export_to_pdf",
    "export_to_mpp",
    "MppTemplateError",
    "analyze_plan",
    "get_next_working_day",
    "add_working_days",
    "parse_duration",
    "extract_metadata",
    "detect_dependency_loops",
    "schedule_tasks",
    "render_custom_timeline",
    "calculate_rag_status",
    "rag_status_to_colour",
    "parse_resource_mappings",
    "parse_resource_roles",
    "parse_stakeholders_from_frontmatter",
    "calculate_evm",
    "natural_language_to_yaml",
    "inherit_summary_resources",
    "parse_recurrence",
    "generate_recurrence_occurrences",
    # Format converter
    "convert_plan_format_to_standard",
    "extract_title_from_frontmatter",
    "extract_highlights",
    "strip_highlights",
    "generate_highlights_text",
    "update_plan_highlights",
    "extract_raid_log",
    "strip_raid_log",
    "parse_raid_markdown",
    "generate_raid_log_text",
    "update_plan_raid_log",
    "extract_budget",
    "strip_budget",
    "parse_budget_markdown",
    "extract_comms_plan",
    "strip_comms",
    "parse_comms_markdown",
    "generate_comms_plan_text",
    "update_plan_comms",
    "export_comms_to_docx",
    "extract_baseline",
    "strip_baseline",
    "parse_baseline_markdown",
    "generate_baseline_text",
    "update_plan_baseline",
    "extract_benefits",
    "strip_benefits",
    "parse_benefits_markdown",
    "extract_lessons",
    "strip_lessons",
    "parse_lessons_markdown",
    "generate_lessons_text",
    "update_plan_lessons",
    "extract_whiteboard",
    "strip_whiteboard",
    "parse_whiteboard_markdown",
    "validate_whiteboard_rows",
    "generate_whiteboard_text",
    "update_plan_whiteboard",
    "extract_parking_lot",
    "strip_parking_lot",
    "parse_parking_lot_markdown",
    "generate_parking_lot_text",
    "update_plan_parking_lot",
    # Excel importer
    "analyze_workbook",
    "convert_excel_to_markdown",
    "convert_planner_to_markdown",
    "detect_planner_worksheet",
    "parse_planner_duration",
    "parse_planner_dependency",
    # MS Project
    "export_to_msproject_xml",
    "import_from_msproject_xml",
    "import_from_mpp",
    "_check_mpp_available",
    "_check_mpxj_available",
    # Front matter parser
    "FrontMatterParser",
]
