#!/usr/bin/env node
// Generate the Penpot-owned design tokens in visual-system.css from the
// Penpot token export in docs/design/tokens/ (#1318, epic #1317).
//
// Penpot is the source of truth for the design tokens. A designer changes a
// token in Penpot, exports the token sets (Design -> Tokens -> Export, multiple
// files) over docs/design/tokens/, and runs
//
//     npm run design:tokens            # rewrite the generated block
//     npm run design:tokens -- --check # fail if the CSS and the JSON disagree
//
// The generated block sits between the two MARKER comments in
// visual-system.css. Everything outside it is hand-written, including the few
// code-owned tokens Penpot cannot hold (CODE_OWNED below).
//
// ## The translation
//
// Penpot does not store tokens the way the stylesheet does, so this is not a
// copy. Each rule below maps a Penpot value back to the CSS the app already
// used, without changing a computed value:
//
//   - A name is `--np-<name>`, except a token in the `legacy` group, which is
//     one of the unprefixed bridge names (`legacy.bg-primary` is
//     `--bg-primary`). `--np-text-muted` and `--text-muted` are different
//     colours, which is why the group exists.
//   - A reference (`{accent-ink}`) is `var(--np-accent-ink)`, and arithmetic on
//     references (`{a} + {b}`) is `calc()`. References are what keep the dark
//     theme working: `--np-elevation-1` is `0 1px 2px var(--np-shadow-tint)`,
//     and the tint is what changes with the theme.
//   - `fontSizes` are px at a 16px base, and the stylesheet's type scale is in
//     em on purpose (see the comment on --np-text-75), so 17.6 is `1.1em`.
//   - `fontFamilies` hold a family and its generic fallback. The full stacks,
//     with the platform fonts in between, live in FONT_STACKS.
//   - `shadow` is a list of layer objects with unitless px lengths.
//   - A value Penpot cannot express at all is in CSS_VALUES, keyed on the
//     Penpot value it stands in for. Change the token in Penpot and the entry
//     stops applying.
//
// ## Which tokens the dark block declares
//
// The light block declares every token in `core` and `color-light`. The dark
// block declares a `color-dark` token when its value differs from the light
// one, or when it is a reference: `--np-success: var(--np-sage)` has to be
// restated under [data-theme="dark"] so it resolves against that scope's
// --np-sage wherever the attribute is set.

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

const ROOT = new URL('..', import.meta.url).pathname
export const TOKENS_DIR = join(ROOT, 'docs/design/tokens')
export const STYLESHEET = join(ROOT, 'packages/noodle-web/src/noodle_web/static/visual-system.css')

export const MARKER_START = '/* BEGIN PENPOT TOKENS -- generated by `npm run design:tokens` from docs/design/tokens/.'
export const MARKER_END = '/* END PENPOT TOKENS */'

// Tokens the stylesheet owns, because Penpot has no type that can hold them:
// its colour tokens take one colour, not a gradient, and it has no duration or
// easing token. They are hand-written in visual-system.css, outside the
// generated block, and `--check` fails if one turns up in the JSON or goes
// missing from the CSS. This list is the one place they are named.
export const CODE_OWNED = [
	'--np-anim-duration-fast',
	'--np-anim-duration',
	'--np-anim-duration-slow',
	'--np-anim-easing',
	'--np-danger-gradient',
	'--np-success-gradient',
	'--np-info-gradient',
]

// Penpot's fontFamilies token is the family and its generic fallback. The
// stylesheet carries the platform fonts in between, which a design file has no
// use for. Keyed on the primary family: pick a different font in Penpot and
// its own list is used instead.
export const FONT_STACKS = {
	'Newsreader': "'Newsreader', Georgia, serif",
	'Instrument Sans': "'Instrument Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
	'IBM Plex Mono': "'IBM Plex Mono', 'DejaVu Sans Mono', monospace",
}

// Values Penpot cannot express, keyed by token and by the Penpot value that
// stands in for them. The stand-in only applies while Penpot still holds it.
export const CSS_VALUES = {
	// Penpot's border radius takes a length, not a percentage. 9999px draws a
	// circle on a square element, as 50% does; on anything else 50% is an
	// ellipse and 9999px a stadium, so the CSS keeps 50%.
	'radius-circle': { penpot: '9999px', css: '50%' },
}

// fontSizes in Penpot are px; the stylesheet's type scale is em.
const FONT_SIZE_BASE_PX = 16

const GENERIC_FAMILIES = new Set(['serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui', 'ui-serif', 'ui-sans-serif', 'ui-monospace', 'math', 'emoji', 'fangsong'])

const INDENT = '    '

export function cssName(path) {
	if (path.startsWith('legacy.')) return `--${path.slice('legacy.'.length)}`
	return `--np-${path.replace(/\./g, '-')}`
}

// Every token in a set, flattened to dotted paths, in file order.
export function flattenSet(node, prefix = '') {
	const out = []
	for (const [key, value] of Object.entries(node)) {
		if (key.startsWith('$') || value === null || typeof value !== 'object') continue
		const path = prefix ? `${prefix}.${key}` : key
		if ('$value' in value) out.push({ path, type: value.$type, value: value.$value, description: value.$description ?? '' })
		else out.push(...flattenSet(value, path))
	}
	return out
}

export function loadTokens(dir = TOKENS_DIR) {
	const read = (name) => JSON.parse(readFileSync(join(dir, name), 'utf8'))
	const metadata = read('$metadata.json')
	const sets = {}
	for (const name of metadata.tokenSetOrder) sets[name] = flattenSet(read(`${name}.json`))
	return { metadata, sets }
}

const REF = /\{([^{}]+)\}/g

function refsToVars(value) {
	return value.replace(REF, (_, path) => `var(${cssName(path.trim())})`)
}

// The string leaves of a value: a shadow is a list of layer objects.
function strings(value) {
	if (typeof value === 'string') return [value]
	if (Array.isArray(value)) return value.flatMap(strings)
	if (value && typeof value === 'object') return Object.values(value).flatMap(strings)
	return []
}

function refsIn(value) {
	return strings(value).flatMap((s) => [...s.matchAll(REF)].map((m) => m[1].trim()))
}

function hasRef(value) {
	return refsIn(value).length > 0
}

// A dimension: `{a} + {b}` is calc(), `{a}` is var(), a bare number is px.
function dimension(value) {
	const v = String(value).trim()
	if (v.includes('{')) {
		const replaced = refsToVars(v)
		return /^\{[^{}]+\}$/.test(v) ? replaced : `calc(${replaced})`
	}
	if (/^-?\d*\.?\d+$/.test(v)) return Number(v) === 0 ? '0' : `${v}px`
	return v
}

function fontSize(value) {
	const v = String(value).trim()
	if (v.includes('{')) return dimension(v)
	if (!/^\d*\.?\d+$/.test(v)) return v // already carries a unit
	const em = Number((Number(v) / FONT_SIZE_BASE_PX).toFixed(4))
	return `${em}em`
}

function fontFamily(value) {
	const list = Array.isArray(value) ? value : String(value).split(',').map((s) => s.trim().replace(/^['"]|['"]$/g, ''))
	const stack = FONT_STACKS[list[0]]
	if (stack) {
		// Only while every family Penpot names is still in the stack, in order.
		const families = stack.split(',').map((s) => s.trim().replace(/^['"]|['"]$/g, ''))
		let i = 0
		for (const family of families) if (family === list[i]) i++
		if (i === list.length) return stack
	}
	// Generic families and keywords like -apple-system go bare; names are quoted.
	return list.map((f) => (GENERIC_FAMILIES.has(f) || f.startsWith('-') ? f : `'${f}'`)).join(', ')
}

function shadow(value) {
	if (typeof value === 'string') return refsToVars(value)
	const layers = Array.isArray(value) ? value : [value]
	return layers.map((layer) => {
		const parts = [dimension(layer.offsetX ?? 0), dimension(layer.offsetY ?? 0), dimension(layer.blur ?? 0)]
		const spread = dimension(layer.spread ?? 0)
		if (spread !== '0') parts.push(spread)
		parts.push(refsToVars(String(layer.color)))
		if (layer.inset === true || layer.inset === 'true') parts.unshift('inset')
		return parts.join(' ')
	}).join(', ')
}

export function toCss(token) {
	const override = CSS_VALUES[token.path]
	if (override && String(token.value) === override.penpot) return override.css
	switch (token.type) {
		case 'fontSizes': return fontSize(token.value)
		case 'fontFamilies': return fontFamily(token.value)
		case 'shadow': return shadow(token.value)
		case 'borderRadius':
		case 'borderWidth':
		case 'dimension':
		case 'sizing':
		case 'spacing':
			return dimension(token.value)
		default:
			return typeof token.value === 'string' ? refsToVars(token.value) : String(token.value)
	}
}

function comment(text, indent) {
	const lines = text.replace(/\s+$/, '').split('\n')
	return lines.map((line, i) => {
		const lead = i === 0 ? `${indent}/* ` : line ? `${indent}   ` : ''
		const tail = i === lines.length - 1 ? ' */' : ''
		return `${lead}${line}${tail}`.replace(/\s+$/, (m) => (tail ? m : ''))
	}).join('\n')
}

function declarations(tokens) {
	const out = []
	for (const [i, token] of tokens.entries()) {
		if (token.description) {
			if (i > 0) out.push('')
			out.push(comment(token.description, INDENT))
		}
		out.push(`${INDENT}${cssName(token.path)}: ${toCss(token)};`)
	}
	return out.join('\n')
}

// Which sets are the light and dark theme, from $themes.json.
function themeSets(dir) {
	const themes = JSON.parse(readFileSync(join(dir, '$themes.json'), 'utf8'))
	const enabled = (name) => {
		const theme = themes.find((t) => t.name.toLowerCase() === name)
		if (!theme) throw new Error(`$themes.json has no "${name}" theme`)
		return Object.entries(theme.selectedTokenSets).filter(([, s]) => s === 'enabled' || s === 'source').map(([set]) => set)
	}
	return { light: enabled('light'), dark: enabled('dark') }
}

export function problems(dir = TOKENS_DIR) {
	const { sets } = loadTokens(dir)
	const out = []
	const seen = new Map()
	for (const [set, tokens] of Object.entries(sets)) {
		for (const t of tokens) {
			const name = cssName(t.path)
			if (CODE_OWNED.includes(name)) out.push(`${name} is code-owned (CODE_OWNED in scripts/design-tokens.mjs) but is in the ${set} token set`)
			for (const ref of refsIn(t.value)) {
				if (!Object.values(sets).some((ts) => ts.some((x) => x.path === ref))) out.push(`${set}/${t.path} refers to {${ref}}, which no set defines`)
			}
			seen.set(name, [...(seen.get(name) ?? []), set])
		}
	}
	const { light, dark } = themeSets(dir)
	for (const [name, inSets] of seen) {
		for (const theme of [light, dark]) {
			const n = inSets.filter((s) => theme.includes(s)).length
			if (n > 1) out.push(`${name} is defined in more than one set of the same theme (${inSets.join(', ')})`)
		}
	}
	return out
}

export function generate(dir = TOKENS_DIR) {
	const { metadata, sets } = loadTokens(dir)
	const { light, dark } = themeSets(dir)
	const order = metadata.tokenSetOrder
	const lightTokens = order.filter((s) => light.includes(s)).flatMap((s) => sets[s])
	const lightByPath = new Map(lightTokens.map((t) => [t.path, t]))
	const darkOnly = order.filter((s) => dark.includes(s) && !light.includes(s)).flatMap((s) => sets[s])
	const darkTokens = darkOnly.filter((t) => {
		const l = lightByPath.get(t.path)
		return !l || hasRef(t.value) || toCss(l) !== toCss(t)
	})

	return [
		`${MARKER_START}`,
		'   Change these in Penpot, not here: see docs/design/contributing.md. */',
		':root {',
		declarations(lightTokens),
		'}',
		'/* The handoff specifies light colours; these warm dark counterparts preserve',
		'   semantic roles and ink-on-marigold buttons without purple/blue surfaces. */',
		'[data-theme="dark"] {',
		declarations(darkTokens),
		'}',
		MARKER_END,
	].join('\n')
}

export function splitStylesheet(css) {
	const start = css.indexOf(MARKER_START)
	const end = css.indexOf(MARKER_END)
	if (start === -1 || end === -1 || end < start) {
		throw new Error(`visual-system.css has no generated block: expected "${MARKER_START}" ... "${MARKER_END}"`)
	}
	return { before: css.slice(0, start), block: css.slice(start, end + MARKER_END.length), after: css.slice(end + MARKER_END.length) }
}

// Custom properties declared in some CSS, comments stripped.
function declaredNames(css) {
	const names = new Set()
	for (const m of css.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/(?:^|[;{\s])(--[a-zA-Z][a-zA-Z0-9-]*)\s*:/g)) names.add(m[1])
	return names
}

// Everything that is wrong with the stylesheet, as sentences. Empty is good.
export function check({ dir = TOKENS_DIR, stylesheet = STYLESHEET } = {}) {
	const out = problems(dir)
	const css = readFileSync(stylesheet, 'utf8')
	let parts
	try {
		parts = splitStylesheet(css)
	} catch (err) {
		return [...out, err.message]
	}
	if (parts.block !== generate(dir)) {
		out.push('the generated block in visual-system.css does not match docs/design/tokens/: '
			+ 'either the JSON changed and `npm run design:tokens` was not run, or a Penpot-owned token was edited by hand')
	}
	const owned = new Set(Object.values(loadTokens(dir).sets).flat().map((t) => cssName(t.path)))
	const outside = declaredNames(parts.before + parts.after)
	for (const name of outside) {
		if (owned.has(name)) out.push(`${name} is a Penpot-owned token but is also declared outside the generated block of visual-system.css; change it in Penpot instead`)
	}
	for (const name of CODE_OWNED) {
		if (!outside.has(name)) out.push(`${name} is code-owned but is not declared outside the generated block of visual-system.css`)
	}
	return out
}

function option(argv, flag, fallback) {
	const i = argv.indexOf(flag)
	return i === -1 ? fallback : argv[i + 1]
}

function main(argv) {
	// --tokens and --stylesheet point it elsewhere, which is how the tests
	// check that a tampered copy fails.
	const dir = option(argv, '--tokens', TOKENS_DIR)
	const stylesheet = option(argv, '--stylesheet', STYLESHEET)
	if (argv.includes('--check')) {
		const found = check({ dir, stylesheet })
		if (found.length) {
			console.error(`design tokens: ${found.length} problem(s)\n  ${found.join('\n  ')}\n\n`
				+ 'Tokens are changed in Penpot: export them over docs/design/tokens/ and run '
				+ '`npm run design:tokens`. See docs/design/contributing.md.')
			return 1
		}
		console.log('design tokens: visual-system.css matches docs/design/tokens/')
		return 0
	}
	const found = problems(dir)
	if (found.length) {
		console.error(`design tokens: ${found.length} problem(s) in the token export\n  ${found.join('\n  ')}`)
		return 1
	}
	const css = readFileSync(stylesheet, 'utf8')
	const { before, after } = splitStylesheet(css)
	const next = before + generate(dir) + after
	if (next === css) {
		console.log('design tokens: visual-system.css already up to date')
	} else {
		writeFileSync(stylesheet, next)
		console.log('design tokens: wrote the generated block of visual-system.css')
	}
	return 0
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) process.exit(main(process.argv.slice(2)))
