#!/usr/bin/env node
/**
 * Copy the pinned `jszip` release into static/vendor/jszip, and generate a
 * tiny ES module shim alongside it.
 *
 * jszip ships no ES module build — only a UMD bundle (dist/jszip.min.js)
 * that assigns `globalThis.JSZip` when it finds no `module`/`define` to
 * satisfy, i.e. when it is evaluated as a real ES module (ESM has none of
 * `module`/`exports`/`define` in scope).
 *
 * Both the bundle and the shim below are vendored with a `.mjs` extension
 * rather than `.js` specifically to force that: Node picks a plain `.js`
 * file's module system from the nearest package.json (this repo doesn't
 * declare "type": "module") or, failing that, a "does it parse as
 * CommonJS" heuristic — and either way that leaves the UMD bundle loading
 * as CommonJS (`module.exports = ...`) rather than assigning the global the
 * shim reads. `.mjs` is unconditionally ESM, in the browser and under Node
 * alike, so both take the same "assign to the global" branch.
 *
 * The shim exists because pptxgenjs's ES module build imports `jszip` by
 * bare specifier, which Node resolves against node_modules but the browser
 * rejects outright (issue #977 / kevinmcaleer/Snakie#977) — see
 * scripts/vendor-pptxgenjs.mjs, which rewrites that bare import to a
 * relative path pointing at this shim.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { vendorRoot, vendor } from "./vendor-lib.mjs";

vendor({
  pkg: "jszip",
  dir: "jszip",
  files: {
    "dist/jszip.min.js": "jszip.min.mjs",
    "LICENSE.markdown": "LICENSE",
  },
});

const target = join(vendorRoot, "jszip");
const shim = `/**
 * A minimal ES module wrapper around the vendored UMD build (jszip.min.mjs).
 *
 * jszip does not publish an ES module build. Its UMD wrapper assigns
 * \`globalThis.JSZip\` whenever it finds no \`module\`/\`define\` to satisfy,
 * which is the case here because jszip.min.mjs is always loaded as a real
 * ES module (see scripts/vendor-jszip.mjs for why it needs the .mjs
 * extension to guarantee that under Node too) — so importing it for its
 * side effect and re-exporting the global is enough to make it a real ES
 * module, in the browser and under Node alike. Generated by
 * scripts/vendor-jszip.mjs; do not edit by hand.
 */
import "./jszip.min.mjs";

export default globalThis.JSZip;
`;
writeFileSync(join(target, "jszip.esm.mjs"), shim);

const version = readFileSync(join(target, "VERSION"), "utf8").trim();
console.log(`generated static/vendor/jszip/jszip.esm.mjs for jszip ${version}`);
